/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package work.chiro.egui;

import com.sun.jna.Native;

public class App {
    public static void main(String[] args) {
        String pwd = System.getProperty("user.dir");
        System.out.printf("pwd: %s", pwd);
        LibEGui egui = Native.load(String.format("%s/../target/debug/libegui.so", pwd), LibEGui.class);
        System.out.println("egui.test(1, 2) = " + egui.test(1, 2));
    }
}
