/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package work.chiro.egui;

import com.sun.jna.Native;
import com.sun.jna.Pointer;
import org.lwjgl.opengl.GL;
import org.lwjgl.opengl.awt.GLData;

import javax.swing.*;
import java.awt.*;
import java.util.concurrent.Semaphore;
import java.util.concurrent.TimeUnit;

public class App {
    static Semaphore signalTerminate = new Semaphore(0);
    static Semaphore signalTerminated = new Semaphore(0);
    private final JFrame frame;
    private final LibEgui lib;
    private Pointer ui;

    public static void doTerminate() {
        // request the cleanup
        signalTerminate.release();
        try {
            // wait until the thread is done with the cleanup
            boolean _i = signalTerminated.tryAcquire(300, TimeUnit.MILLISECONDS);
            // signalTerminated.acquire();
        } catch (InterruptedException ignored) {
        }
    }

    public App() {
        frame = new JFrame("AWT test") {
            @Override
            public void dispose() {
                doTerminate();
                super.dispose();
            }
        };
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLayout(new BorderLayout());
        frame.setPreferredSize(new Dimension(600, 600));
        GLData data = new GLData();
        data.samples = 4;
        data.swapInterval = 0;
        String pwd = System.getProperty("user.dir");
        lib = Native.load(String.format("%s/../target/debug/libegui.so", pwd), LibEgui.class);
        EguiGL egui = new EguiGL();
        MyGLCanvas canvas = new MyGLCanvas(data, egui::init);
        ui = lib.egui_create(() -> {
            if (!canvas.isValid()) {
                GL.setCapabilities(null);
                return false;
            }
            canvas.beforeRender();
            if (!canvas.getInitCalled()) {
                canvas.initGL();
                canvas.setInitCalled();
                return false;
            }
            return egui.beforeHandler.callback();
        }, egui.meshHandler, () -> {
            egui.afterHandler.callback();
            canvas.afterRender();
        });
        frame.add(canvas, BorderLayout.CENTER);
        frame.pack();
        frame.setVisible(true);
        frame.transferFocus();
        Thread thread = new Thread(() -> lib.egui_run_block(ui));
        thread.setDaemon(true);
        thread.start();
    }

    public void run() throws InterruptedException {
        Thread.sleep(3000);
        System.out.println("all done");
        frame.dispose();
        System.exit(0);
    }

    public static void main(String[] args) throws InterruptedException {
        App app = new App();
        app.run();
    }
}
